language: node_js
node_js:
  - "stable"
branches:
  only:
    - /.*/
install:
  - npm install
cache:
  -npm install
services:
  - postgresql
before_script:
  - npm install -g sequelize
  - npm install -g nyc
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER raphael WITH PASSWORD 'Password';" -U postgres
  
after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
env:
  global:
    - SECRET=play123
    - DATABASE_USER=raphael
    - NODE_ENV=test