language: node_js
node_js:
  - node
install:
  - npm install
script: 
  - npm test
after_success:
  - codeclimate < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure:93a4f79ded506e40b55a56d4bcb6acc992ae4555d145608d01fe52ce4da9931e
      