language: node_js
node_js:
  - "stable"
branches:
  only:
    - /.*/
install:
  - npm install
script:
  - npm test
cache:
  -npm install
services:
  - postgresql
before_script:
  - psql -c 'create database postit;' -U postgres
  
after_success:
  - npm run coveralls
env:
  global:
    - SECRET=play123
    - DB_USER=postgres
    - NODE_ENV=test