language: node_js
node_js:
  - "stable"
branches:
  only:
    - /.*/
install:
  - npm install
cache:
  -npm install
services:
  - postgresql
before_script:
  - npm install -g sequelize
  - psql -c "CREATE DATABASE slack;" -U postgres
  - psql -c "CREATE USER raphael WITH PASSWORD 'Password';" -U postgres
  - NODE_ENV=test npm run test
  
after_success:
  - npm run coveralls
env:
  global:
    - SECRET=play123
    - DATABASE_USER=andeladeveloper
    - NODE_ENV=test